### ISSUE TITLE
Launch TODO

### ISSUE THREAD

**Issue by mischacolley** [mischacolley/sandracolley.com.au#1]
- [ ] Register Domain 
- [ ] Connect Instagram feed and work out hook to rebuild on new posts
- [ ] Configure SEO/Social Tags for posts/pages
- [ ] Finish Forestry formatting for posts
- [ ] Think about landing pages 
- [ ] Connect contact form
- [ ] Submit Sitemap
- [ ] Setup Analytics
- [ ] Setup Google Web Master Tools
- [ ] Setup Google Business Listing
